ETFE-3635 Added NRS payload for explain a delay
hmrc/emcs-tfe pull request #144
Opened 2024-04-08 13:07 UTC by grahampaulcook

2024-04-08 14:02 UTC, LewisMitchell requested changes

2024-04-08 14:13 UTC, grahampaulcook commented on test/uk/gov/hmrc/emcstfe/controllers/SubmitExplainDelayControllerSpec.scala
> +          }
Addressed at https://github.com/hmrc/emcs-tfe/pull/144/commits/4ef2d1cfbb50667882643d220c404b8dad18419e#diff-3dd0e9c4ceba570f882389650900fca52c560658ca1e17a3d5285bfd173fd752R131

2024-04-08 14:18 UTC, LewisMitchell commented on test/uk/gov/hmrc/emcstfe/controllers/SubmitExplainDelayControllerSpec.scala
> +          }
This can be removed as its a duplicate of the last test in the file

2024-04-09 08:52 UTC, LewisMitchell approved these changes

2024-04-09 08:52 UTC, merged